/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtelierRouteImport } from './routes/atelier'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as CommissionRouteImport } from './routes/commission'
import { Route as LogoRouteImport } from './routes/logo'
import { Route as GuitarSlugRouteImport } from './routes/guitar.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierRoute = AtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissionRoute = CommissionRouteImport.update({
  id: '/commission',
  path: '/commission',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoRoute = LogoRouteImport.update({
  id: '/logo',
  path: '/logo',
  getParentRoute: () => rootRouteImport,
} as any)
const GuitarSlugRoute = GuitarSlugRouteImport.update({
  id: '/guitar/$slug',
  path: '/guitar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/collection': typeof CollectionRoute
  '/commission': typeof CommissionRoute
  '/logo': typeof LogoRoute
  '/guitar/$slug': typeof GuitarSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/collection': typeof CollectionRoute
  '/commission': typeof CommissionRoute
  '/logo': typeof LogoRoute
  '/guitar/$slug': typeof GuitarSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/collection': typeof CollectionRoute
  '/commission': typeof CommissionRoute
  '/logo': typeof LogoRoute
  '/guitar/$slug': typeof GuitarSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/atelier' | '/collection' | '/commission' | '/logo' | '/guitar/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/atelier' | '/collection' | '/commission' | '/logo' | '/guitar/$slug'
  id:
    | '__root__'
    | '/'
    | '/atelier'
    | '/collection'
    | '/commission'
    | '/logo'
    | '/guitar/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtelierRoute: typeof AtelierRoute
  CollectionRoute: typeof CollectionRoute
  CommissionRoute: typeof CommissionRoute
  LogoRoute: typeof LogoRoute
  GuitarSlugRoute: typeof GuitarSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier': {
      id: '/atelier'
      path: '/atelier'
      fullPath: '/atelier'
      preLoaderRoute: typeof AtelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commission': {
      id: '/commission'
      path: '/commission'
      fullPath: '/commission'
      preLoaderRoute: typeof CommissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logo': {
      id: '/logo'
      path: '/logo'
      fullPath: '/logo'
      preLoaderRoute: typeof LogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guitar/$slug': {
      id: '/guitar/$slug'
      path: '/guitar/$slug'
      fullPath: '/guitar/$slug'
      preLoaderRoute: typeof GuitarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtelierRoute: AtelierRoute,
  CollectionRoute: CollectionRoute,
  CommissionRoute: CommissionRoute,
  LogoRoute: LogoRoute,
  GuitarSlugRoute: GuitarSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
